// https://www.learncpp.com/cpp-tutorial/uncaught-exceptions-catch-all-handlers

#include <iostream>

struct GameSession {
	// Game session data here
};

void runGame(GameSession&) {
	throw 1;
}

void saveGame(GameSession&) {
	// Save user's game here
}

class DummyException {  // a dummy class that can't be instantiated
	DummyException() = delete;
};

int main() {
	GameSession session {};

	try {
		runGame(session);
	}
// #define NDEBUG 1
#ifndef NDEBUG  // if we're in release node
	catch(...) {	// compile in the catch-all handler
		std::cerr << "Abnormal termination\n";
	}
#else	// in debug mode, compile in a catch that will never be hit (for syntactic reasons)
	catch(DummyException) {}
#endif

	saveGame(session); // save the user's game (even if catch-all handler was hit)

	return 0;
}